package hackphone.phone.registering.stateMachine;

enum StateList {
    REGISTER_INITIALIZE,
    REGISTER_INITIALIZE_WAIT_FOR_UNAUTHORIZED,
    REGISTER_INITIALIZE_SENDING_REGISTER_WITH_AUTHORIZATION;
}
